services:
  - type: web
    name: error-monitor-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        sync: false
      - key: ENDPOINT_PATH
        value: "/endpoint"
      - key: MAX_LOGS
        value: "100"
      - key: REDIS_URL
        fromService:
          name: error-monitor-redis
          type: redis
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

  - type: redis
    name: error-monitor-redis
    ipAllowList: []
    maxmemoryPolicy: noeviction
    plan: free 